= Jeremiah Michaels

....
415-309-7476
mrjeremiahmichaels@icloud.com
....

Building information architecture with DITA. Creating release notes, user guides, and feature documentation.

== Skills
Markdown, DITA, HTML, CSS, Oxygen XML Editor, AsciiDoc, Confluence, Jira, Swagger, Git

== Experience
=== Senior Technical Writer, Magnit Global, December 2019 to Present
Built the entire end-to-end documentation flow for a staffing services company with a
vendor-neutral VMS. Established documentation best practices and integration with the
Product Management team using Atlassian Jira and Confluence.
.Deliverables include
* Customized (HTML/CSS) WebHelp user guides with corporate branding and security
using Oxygen XML Editor
* Customized (CSS) PDF user guides with corporate branding using Oxygen XML Editor
* Release notes for monthly product releases (MS Word)
* API Documentation in YAML format (Swagger Editor)
* Translated the entire documentation set into Spanish using machine translation (DeepL)


=== Senior Techncial Writer, Moody's, October 2015 - December 2019
Created and maintained product documentation for a financial services company.
.Deliverables included
* User guides (web and PDF) for a quarterly-delivered analytics tool
* API documentation (web and PDF)
Participated in a project to migrate all XML-formatted documentation to a web-based
platform (Confluence).
.Project deliverables included
* Designed and implemented an authentication method for the web portal
* Designed and implemented a Confluence workflow for creating, reviewing, and
obtaining signatures from stakeholders

=== Technical Writer, Ensenta Corporation, October 2014 - October 2015
Created internal and external documentation for a financial services software company.
.Deliverables included
* Internal knowledge base for configuration and support teams (Oxygen XML Editor)
* API documentation (PDF)
* Mobile app configuration guide and release notes (PDF)
* Network diagrams for the infrastructure team (Visio)

=== Instructional Designer, Calypso Technology, April 2013 - October 2014
Created training materials for a financial services software company. Worked with SMEs to
create courses and presentations for training purposes.
.Deliverables included
* Training manuals for courses (PDF)
* Training laptops with course work configured in the database (SQL)

=== Technical Writer, Calypso Technology, June 2011 - April 2013
Created product documentation for a financial services software company.
.Deliverables included
* Application user guides (MadCap Flare)
* Application release notes (MS Word)


== Education
* MA, Communication and Leadership, Gonzaga University, 2011 - 2013
* BA, Techncial and Professional Writing, San Francisco State University, 2006 - 2009
